---
- hosts: all
  become: true
  tasks:
    - name: Set default remote_user if not defined
      set_fact:
        ansible_user: "{{ ansible_user | default('root') }}"
      when: ansible_user is not defined

  roles:

    - role: "{{ playbook_dir }}"
      when: ansible_user is defined
